name: CI for Python and C# Project

on:
  pull_request:
    branches:
      - main

jobs:
  python-tests:
    name: Python Lint & Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Python Environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -e .

      - name: Run flake8
        run: |
          source venv/bin/activate
          flake8 src

      - name: Run black (check)
        run: |
          source venv/bin/activate
          black --check src